"""Core module exports."""

from src.core.config import Settings, get_settings, settings
from src.core.logging import logger, setup_logging
from src.core.exceptions import (
    CrewException,
    # HotspotAgent exceptions
    HotspotException,
    RateLimitError,
    ForbiddenError,
    TimeoutError,
    JSONDecodeError,
    # ContentAgent exceptions
    ContentException,
    LLMTimeoutError,
    LLMFormatError,
    EmptyContentError,
    ComplianceError,
    TokenLimitError,
    AuthenticationError,
    DiskFullError,
    ImageGenTimeoutError,
    ImageComplianceError,
    # PublishAgent exceptions
    PublishException,
    CookieExpiredError,
    CaptchaRequiredError,
    PublishRateLimitError,
    ContentRejectedError,
    BrowserCrashError,
    ElementNotFoundError,
    NetworkTimeoutError,
    # AnalyticsAgent exceptions
    AnalyticsException,
    ContentNotFoundError,
    DataFormatError,
    # Database exceptions
    DatabaseException,
    IntegrityError,
    PoolExhaustedError,
    DeadlockError,
)
from src.core.error_handling import (
    Result,
    Success,
    Error,
    success,
    error,
    from_exception,
    safe_execute,
    safe_execute_async,
    ErrorContext,
    retry_on_transient,
    retry_on_llm_error,
    CircuitBreaker,
    fallback,
    jitter,
)
from src.core.auth import (
    User,
    UserRole,
    JWTManager,
    TokenPayload,
    EncryptionManager,
    CookieManager,
    AuthContext,
    require_auth,
    APIKeyManager,
)
from src.core.audit import (
    AuditLogger,
    AuditEventType,
    AuditSeverity,
    AuditEvent,
    get_audit_logger,
    audit_log,
)

__all__ = [
    # Config
    "Settings",
    "get_settings",
    "settings",
    # Logging
    "logger",
    "setup_logging",
    # Exceptions
    "CrewException",
    "HotspotException",
    "RateLimitError",
    "ForbiddenError",
    "TimeoutError",
    "JSONDecodeError",
    "ContentException",
    "LLMTimeoutError",
    "LLMFormatError",
    "EmptyContentError",
    "ComplianceError",
    "TokenLimitError",
    "AuthenticationError",
    "DiskFullError",
    "ImageGenTimeoutError",
    "ImageComplianceError",
    "PublishException",
    "CookieExpiredError",
    "CaptchaRequiredError",
    "PublishRateLimitError",
    "ContentRejectedError",
    "BrowserCrashError",
    "ElementNotFoundError",
    "NetworkTimeoutError",
    "AnalyticsException",
    "ContentNotFoundError",
    "DataFormatError",
    "DatabaseException",
    "IntegrityError",
    "PoolExhaustedError",
    "DeadlockError",
    # Error handling
    "Result",
    "Success",
    "Error",
    "success",
    "error",
    "from_exception",
    "safe_execute",
    "safe_execute_async",
    "ErrorContext",
    "retry_on_transient",
    "retry_on_llm_error",
    "CircuitBreaker",
    "fallback",
    "jitter",
    # Auth
    "User",
    "UserRole",
    "JWTManager",
    "TokenPayload",
    "EncryptionManager",
    "CookieManager",
    "AuthContext",
    "require_auth",
    "APIKeyManager",
    # Audit
    "AuditLogger",
    "AuditEventType",
    "AuditSeverity",
    "AuditEvent",
    "get_audit_logger",
    "audit_log",
]
